#!usr/bin/env/python

import requests

print requests.__version__

response = requests.get("https://raw.githubusercontent.com/aolin1/404LAB/master/lab1")

print response.text
print response.status_code

